### PR TITLE
Issue #91: added lint test

### LINKED ISSUE #91: As a developper, I want to lint my project
- Missing node lint-test inside this workflow.

### PR DESCRIPTION
**Pull request by ThomasCardin**
- Closes ai-cfia/nachet-frontend#98

### CODE REVIEW

**Comment by ThomasCardin** [comment]
@CFIALeronB Do you have an idea of what is failing in the lint-test?

**Comment by rngadam** [comment]
> @CFIALeronB Do you have an idea of what is failing in the lint-test?

@ThomasCardin 

tsconfig.json specifies an include of src/ but eslint is run as

```
eslint .
```

meaning all directories in the root get tested. should be:

```
eslint src/
```

probably since tsconfig.json, the list of directories to be lint'ed should be passed as parameter and default to src/

**Review by rngadam — CHANGES_REQUESTED** [review]
workflow upstream need change to lint src/

**Comment by ThomasCardin** [comment]
@ibrahim-kabir Here's the workflow that need a fix [this workflow](https://github.com/ai-cfia/github-workflows/blob/main/.github/workflows/workflow-lint-test-node.yml). If you have any questions, let me know :)

**Comment by ThomasCardin** [comment]
FYI: This is the issue https://github.com/ai-cfia/nachet-frontend/blob/91-as-a-developper-i-want-to-lint-my-project/package.json#L47 . Change the `.` to `src/`

**Comment by ThomasCardin** [comment]
> workflow upstream need change to lint src/

This is the issue https://github.com/ai-cfia/nachet-frontend/blob/91-as-a-developper-i-want-to-lint-my-project/package.json#L47 . Change the `.` to `src/` . The workflow is functioning as intended

**Comment by rngadam** [comment]
@ThomasCardin I do not agree that we should ever merge pull requests that are failing the checks. If you do not want to fix the merge than reassign to a developer but do not merge.

image

**Pull request merged**
