### PR TITLE
Refactor Microscope and Capture Functionality into a Single Component

### PR DESCRIPTION
**Pull request by CFIALeronB**
Integrating the previously separate microscope feed and capture functionalities into a unified component. The refactoring involved the following key changes: 
 
1. Interface Update: Modified the `MicroscopeFeed` interface to accept new props that control the active state between the webcam feed and the captured image display. This change simplifies state management and enhances the component's re-usability. 
 
2. Toggle Button Implementation: Introduced a `ToggleButton` component to switch between the live webcam feed and the captured image view. This new component improves code readability and maintainability by encapsulating the common button styling and behaviour. 
 
3. State Management: Implemented a new state variable `isWebcamActive` to determine the visibility of the webcam feed versus the captured image. This state is now managed by the parent component, allowing for centralised control of the UI state.

#56 

**Unified Video Feed/Capture Component before/after screenshots:**

**Before:**

image

_After:_

image
image

### CODE REVIEW

**Review by rngadam — CHANGES_REQUESTED** [review]
pursuant to what we were talking this morning, we should perhaps use VideoFeed instead of Webcam to not introduce additional terminology.

also, can you provide before/after screenshots within your PR for future reference?

and create/update TESTING.md

**Comment by rngadam** [comment]
> > pursuant to what we were talking this morning, we should perhaps use VideoFeed instead of Webcam to not introduce additional terminology.
> > also, can you provide before/after screenshots within your PR for future reference?
> > and create/update TESTING.md
> 
> @rngadam What should the TESTING.md document entail? Is there anything specific you would like me to focus on in the documentation?

@redat97 I found out we don't seem to have documentation around this.

The template should include sample tests that can be manually executed to test the functionality as you've done to test the functionality yourself. We don't have a specific template, but should explain how you would get someone else to test that the functionality you've built are working.

**Comment by nmeraihi** [comment]
Nice work! I like the ideas

**Review by RussellJimmies — APPROVED** [review]
LGTM!

**Pull request merged**
